### ISSUE TITLE
벡엔드 초기 세팅

### ISSUE THREAD

**Issue by leejh7** [BTS-Busan-Trip-Supporter/back-end#1]
## Overview
프로젝트 기본 세팅 설정

## Task
- [x] 필요한 기본 dependency 추가
- [x] application.yaml 파일 작성
- [x] 필요한 디렉토리 만들기
- [x] 템플릿 코드 작성 (Member)
